name: This is a practice for artifacr
on: workflow_dispatch
env:
    TEST: "${{secrets.TEST}}"
    BHEEM: "${{secrets.BHEEM}}"
jobs:
    first:
      runs-on: ubuntu-latest
      steps:
          - name: Print teh envt varibale
            run: echo "This is alphabet ${{env.TEST}}"
          - name: Print the envt variable
            run: echo "This is the value of ${{env.BHEEM}}"
          - name: checkout the branch
            uses: actions/checkout@v3
          - name: install nodeJS
            uses: actions/setup-node@v3
            with:
                node-version: "16.18.0"
          - name: Install dependency
            run: npm install
          - name: Build package
            run: npm run build
          - name: what is in PWD
            run: |
                ls
                pwd
          - name: get the artifacts
            uses: actions/upload-artifact@v3
            with:
                  name: DTM_APP
                  path: |
                        dist
                        index.html
                        package.json
          - name: pwd
            run: |
                ls -la
                pwd

    second:
      needs: first
      runs-on: ubuntu-latest
      steps:
       - name: checkout the brach to the locatuion 
         uses: actions/checkout@v3
       
       - name: copying the artifact to this location 
         uses: actions/download-artifact@v3
         with:
             name: DTM_APP
       - name: Get the pwd and ls
         run: |
             ls
             pwd
